Update docs to dioxus next
DioxusLabs/docsite pull request #202
Opened 2024-01-30 17:36 UTC by ealmloff

This PR updates the docs to match the changes in https://github.com/DioxusLabs/dioxus/pull/1791

2024-01-30 18:08 UTC, marc2332 requested changes

2024-01-30 18:08 UTC, marc2332 commented on docs-src/0.4/en/reference/component_props.md
>  }
```suggestion
fn TitleCard(props: TitleCardProps) -> Element {
    rsx!{
        h1 { "{props.title}" }
    })
}
```

2024-01-30 18:08 UTC, marc2332 commented on docs-src/0.4/en/reference/component_props.md
github doesn't let me review an unchanged line, but anyway, this goes in L130
```rs
#[derive(Props, Clone, PartialEq)]
struct TitleCardProps {
    title: String,
}
```

2024-01-30 18:20 UTC, marc2332 requested changes

2024-01-30 18:20 UTC, marc2332 commented on docs-src/0.4/en/reference/component_props.md
>      })
just noticed this sorry
```suggestion
    }
```

2024-01-30 18:20 UTC, marc2332 commented on docs-src/0.4/en/reference/component_props.md
>      })
```suggestion
    }
```

2024-02-08 21:16 UTC, ealmloff commented
Bumping the dioxus version solves several hydration issues:
Closes #200
Closes #139

2024-02-19 18:05 UTC, ealmloff commented
Dioxus mobile and wry mobile is currently broken with any wry version of `>0.34` (https://github.com/tauri-apps/cargo-mobile2/issues/267)

2024-02-21 18:25 UTC, ealmloff commented
The content is done, but I'm marking this as a draft until I get the static generation working again

2024-02-28 20:24 UTC, ealmloff commented
Prebuilds are working and do not override the previous doc versions

2024-03-02 21:10 UTC, ritzk commented on docs-src/0.5/en/getting_started/mobile.md
> +            .with_min_level(log::Level::Trace)
```suggestion
            .with_max_level(log::LevelFilter::Trace)
```

2024-03-02 21:10 UTC, ritzk commented on docs-src/0.5/en/getting_started/mobile.md
> +> You may also be asked to input your team ID for IOS. You can find your team id [here](https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/) or create a team id by creating
```suggestion
> You may also be asked to input your team ID for IOS. You can find your team id [here](https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/) or create a team id by creating a developer account [here](https://developer.apple.com/help/account/get-started/about-your-developer-account)
```

2024-03-03 01:19 UTC, ealmloff commented on docs-src/0.5/en/getting_started/mobile.md
> +            .with_min_level(log::Level::Trace)
Good catch, thanks!

2024-03-04 18:36 UTC, merged